		var text_default_html = "<span>Drag the images to color channels and observe the resulting image below." 
		+ "<br><br>Touch a region in the electromagnetic spectrum to find out more about this region.</span>";
		
		var text_default_html_DE = "<span>Ziehen Sie die Bilder in die Farbkanäle und beobachten Sie das dabei entstehende Bild." 
		+ "<br><br>Berühren Sie einen Bereich des elektromagnetischen Spektrums um mehr über diesen Bereich herauszufinden.</span>";
		
		var xref = {//english dialog texts 
			gamma: "<b>Gamma-rays</b><br><br> Gamma-rays have wavelengths of less than 60 pm (that’s 0.00000006 mm)."  
			+ " They have the smallest wavelengths and the most energy of any other type of electromagnetic radiation."
			+ "<br><br>They are produced by the hottest and most energetic objects in the Universe, such as neutron stars and pulsars, supernova explosions, and regions around black holes."
			+ " On Earth, gamma waves are generated by nuclear explosions, lightning, and radioactive decay. They can be extremely dangerous to living tissue.", 
			
			xray: "<b>X-rays</b><br><br> X-rays have very small wavelengths of 0.0061 to 8 nm — so small that some x-rays are no bigger than a single atom."
			+ "<br><br>Natural sources of x-rays include lightning, the Sun, active black holes, supernova remnants and stars."
			+ " X-rays are able to travel through parts of the human body like skin, but are partially stopped by denser matter such as bones, creating recogniseable x-ray images of human skeletons.",
			
			ultra: "<b>Ultraviolet light</b><br><br> Ultraviolet light has wavelengths of about 8 nm to about 380 nm (0.000008 to 0.00038 mm)."
			+ "<br><br>Sunlight is the greatest source of ultraviolet radiation. It is invisible to the human eye but has numerous medical and industrial applications on Earth."
			+ " It can damage living tissue but Earth’s atmosphere protects us from most of the ultraviolet radiation coming from space.",
			
			visible: "<b>Visible light</b><br><br> Visible light make up the middle of the electromagnetic spectrum, with wavelengths between 380 nm and 740 nm."
			+ " More generally, visible light is defined as the radiation that is visible to human eyes, covering the colours we see from violet to red."
			+ "<br><br>Natural sources of visible light include very hot objects like the Sun, stars and flames, as well as some biological organisms.",	
			
			infra: "<b>Infrared radiation</b><br><br> Infrared radiation extends from the red edge of the visible spectrum, with wavelengths ranging from 0.0007 mm to 1 mm."
			+ " Anything with a temperature above -268 °C emits infrared radiation. As the human body temperature is 37  °C, it is the main type of radiation emitted by our bodies."
			+ "<br><br>Infrared radiation has longer wavelengths than visible light, so it is less easily scattered and absorbed by dust and gas."
			+ " This means it can be used to observe astronomical objects that are shrouded in dust and gas, like young stars and planets.", 
			
			micro: "<b>Microwaves</b><br><br> Microwaves are a type of electromagnetic radiation with wavelengths ranging from 1 mm to 30 cm."
			+ "<br><br>Natural sources of microwaves include the Sun and the Cosmic Microwave Background."
			+ " Microwaves are very useful for us down here on Earth — they are artificially produced for use in communications, radar, and of course, cooking.",
			
			radio: "<b>Radio waves</b><br><br> Radio waves are at the low-frequency end of the electromagnetic spectrum. They have relatively long wavelengths ranging from 30 cm to 100 km."
			+ "<br><br>Naturally occurring radio waves are generated in some of the most high-energy astronomical events and objects in the Universe, including the supermassive black hole at the centre of the Milky Way."
			+ " Radio waves are also emitted and received by antennas on Earth, and widely used in communications such as radio, TV and mobile phone networks.", 
			
			frequency:"something about frequency...",
			wavelength:"something about wavelengths..."
		};
		
		var xref_DE = {//german dialog texts
			gamma: "<b>Gammastrahlen</b><br><br> Gammastrahlen haben Wellenlängen von weniger als 60 pm (das sind 0,00000006 mm)."
			+ " Sie haben die kleinsten Wellenlängen und die höchste Energie aller Arten elektromagnetischer Strahlung."
			+ "<br><br>Sie werden von den heißesten und energiereichsten Objekten im Universum erzeugt."
			+ " Dazu gehören Neutronensternen und Pulsare, Supernovaexplosionen und die Bereiche rund um Schwarze Löcher."
			+ " Auf der Erde werden Gammastrahlen durch Kernexplosionen, Blitzeinschläge und radioaktiven Zerfall erzeugt. Gammastrahlen können für lebendes Gewebe extrem gefährlich sein.",
			
			xray: "<b>Röntgenstrahlen</b><br><br> Röntgenstrahlen haben sehr kleine Wellenlängen von 0,0061 bis 8 nm — so klein, dass manche Röntgenstrahlen nicht größer als ein einzelnes Atom sind."
			+ "<br><br>Natürliche Quellen von Röntgenstrahlen sind Blitze, die Sonne, aktive Schwarze Löcher, Supernova überreste und Sterne."
			+ " Röntgenstrahlen können durch Teile des menschlichen Körpers wandern, werden aber teilweise durch dichtere Materie wie Knochen gestoppt und erzeugen so Röntgenbilder menschlicher Skelette.", 
			
			ultra: "<b>Ultraviolettes Licht</b><br><br> Ultraviolettes Licht hat Wellenlängen von etwa 8 nm bis etwa 10 nm (0,00038 bis 0,00001 mm)."
			+ "<br><br>Sonnenlicht ist die Hauptquelle für ultraviolette Strahlung. Ultraviolette Licht ist für das menschliche Auge unsichtbar, hat aber zahlreiche medizinische und industrielle Anwendungen auf der Erde."
			+ " Es kann lebendes Gewebe schädigen, aber die Erdatmosphäre schützt uns vor den meisten ultravioletten Strahlen, die aus dem Weltraum kommen.",
			
			visible: "<b>Sichtbares Licht</b><br><br> Das sichtbare Licht bildet die Mitte des elektromagnetischen Spektrums mit Wellenlängen zwischen 380 nm und 740 nm."
			+ " Allgemein wird sichtbares Licht als die Strahlung definiert, die für die menschlichen Augen sichtbar ist. Es deckt alle Farben zwischen violett und rot ab."
			+ "<br><br>Zu den natürlichen Quellen des sichtbaren Lichts gehören sehr heiße Objekte wie Sonne, Sterne und Flammen sowie einige biologische Organismen.",
			
			infra: "<b>Infrarot-Strahlung</b><br><br> Infrarot-Strahlung erstreckt sich vom roten Rand des sichtbaren Spektrums mit Wellenlängen von 0,0007 mm bis 1 mm."
			+ " Alles, was eine Temperatur über -268 °C hat, strahlt Infrarotstrahlung aus. Da die menschliche Körpertemperatur 37 °C beträgt, ist sie die wichtigste Strahlungsart, die von unserem Körper emittiert wird."
			+ "<br><br>Infrarot-Strahlung hat längere Wellenlängen als sichtbares Licht, so dass sie weniger leicht gestreut und von Staub und Gas absorbiert wird."
			+ " Damit können astronomische Objekte beobachtet werden, die von Staub und Gas umhüllt sind, wie junge Sterne und Planeten.", 
			
			micro: "<b>Mikrowellen</b><br><br> Mikrowellen sind eine Art elektromagnetische Strahlung mit Wellenlängen von 1 mm bis 30 cm."
			+ "<br><br>Natürliche Quellen von Mikrowellen sind die Sonne und der kosmische Mikrowellenhintergrund."
			+ " Mikrowellen sind für uns hier auf der Erde sehr nützlich — sie werden künstlich hergestellt, um sie in der Kommunikation, im Radar und natürlich beim Kochen zu verwenden.",
			
			radio: "<b>Radiowellen</b><br><br> Radiowellen befinden sich am niederfrequenten Ende des elektromagnetischen Spektrums. Sie haben relativ lange Wellenlängen von 30 cm bis 100 km."
			+ "<br><br>Natürlich auftretende Radiowellen werden durch einige der energiereichsten astronomischen Ereignisse und Objekte im Universum erzeugt, darunter auch durch das supermassereiche Schwarze Loch im Zentrum der Milchstraße."
			+ " Radiowellen werden auch von Antennen auf der Erde ausgestrahlt und empfangen und sind in Kommunikationsnetzen wie Radio, TV und Mobilfunk weit verbreitet.", 
			
			frequency:"DE something about frequency...",
			wavelength:"DE something about wavelengths..."
		};
